POST localhost:8080/members/signup
Content-Type: application/json

{
    "email": "example@example.com",
    "name": {
        "first": "John",
        "last": "Doe"
    },
    "password": "password123"
}
###
POST localhost:8080/members/signin
Content-Type: application/json

{
"email": "example@example.com",
"password": "password123"
}